ELearnProject/Controllers/QuestionCategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace ELearnProject.Controllers
{
    public class QuestionCategoryController : Controller
    {
        QuestionCategoryManager questionCategoryManager = new QuestionCategoryManager(new EFQuestionCategoryRepository());


        public IActionResult Index()
        {
            var questionCategories = questionCategoryManager.GetAllQuestionCategories();
            return View(questionCategories);
        }

        [HttpGet]
        public IActionResult AddQuestionCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddQuestionCategory(QuestionCategory questionCategory)
        {
            questionCategoryManager.AddQuestionCategory(questionCategory);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UpdateQuestionCategory(int id)
        {
            var questionCategoryName = questionCategoryManager.GetQuestionCategory(id);
            return View(questionCategoryName);
        }

        [HttpPost]
        public IActionResult UpdateQuestionCategory(int id, string questionCategoryName)
        {
            var qctg = questionCategoryManager.GetQuestionCategory(id);
            qctg.QuestionCategoryName = questionCategoryName;
            questionCategoryManager.UpdateQuestionCategory(qctg);
            return RedirectToAction("Index");
        }



        public IActionResult DeleteQuestionCategory(int id)
        {
            var questionCategory = questionCategoryManager.GetQuestionCategory(id);
            questionCategoryManager.DeleteQuestionCategory(questionCategory);
            return RedirectToAction("Index");
        }
    }
}

ELearnProject/Views/QuestionCategory/AddQuestionCategory.cshtml
@using EntityLayer.Concrete
@model QuestionCategory
@{
    ViewData["Title"] = "Soru Kategorisi Ekle";
}
<h1>@ViewData["Title"]</h1>



@using (Html.BeginForm("AddQuestionCategory", "QuestionCategory", FormMethod.Post, new { @class = "form-group" }))
{

    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m => m.QuestionCategoryName, new { @class = "form-control", name = "CategoryName" })
    </div>
    <br />
    <button class="btn btn-success" type="submit">Kategori Ekle</button>
}

ELearnProject/Views/QuestionCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<QuestionCategory>
@{
    ViewData["Title"] = "Soru Kategorisi İşlemleri";
}
<h1>@ViewData["Title"]</h1>


<table class="table table-bordered">
    <tr>
        <th>Kategori Id</th>
        <th>Kategori Adı</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.QuestionCategoryId</td>
            <td>@item.QuestionCategoryName</td>
            <td><a href="QuestionCategory/UpdateQuestionCategory/@item.QuestionCategoryId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="QuestionCategory/DeleteQuestionCategory/@item.QuestionCategoryId" class="btn btn-danger">Sil</a></td>
        </tr>
    }


</table>
<a href="/QuestionCategory/AddQuestionCategory/" class="btn btn-primary">Yeni Soru Kategorisi Ekle</a>

ELearnProject/Views/QuestionCategory/UpdateQuestionCategory.cshtml
@using EntityLayer.Concrete
@model QuestionCategory
@{
    ViewData["Title"] = "Kategori Güncelleme";
}
<h1>@ViewData["Title"]</h1>



@using (Html.BeginForm("UpdateQuestionCategory", "QuestionCategory", FormMethod.Post, new { @class = "form-group" }))
{
    <div>
        <label>Kategori Id</label>
        @Html.TextBoxFor(m => m.QuestionCategoryId, new { @class = "form-control", name = "CategoryId", disabled = "disabled" })
    </div>
    <br />
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m => m.QuestionCategoryName, new { @class = "form-control", name = "CategoryName" })
    </div>
    <br />
    <button class="btn btn-success" type="submit">Kategori Güncelle</button>
}